server:
  port: 8081

employeeUrl: http://localhost:8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemicroservice
    username: root
    password: asher
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: employee-service
